# Generated by Django 5.0.4 on 2024-05-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
        ('recipients', '0002_remove_recipients_mailing_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingsettings',
            name='mailing_recipients',
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='recipients',
            field=models.ManyToManyField(blank=True, null=True, to='recipients.recipients', verbose_name='recipients'),
        ),
    ]
