# Generated by Django 5.0.4 on 2024-05-08 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingmessage',
            name='recipients',
        ),
    ]
