# Generated by Django 5.0.4 on 2024-05-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_remove_mailingsettings_mailing_recipients_and_more'),
        ('recipients', '0002_remove_recipients_mailing_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='recipients',
            field=models.ManyToManyField(to='recipients.recipients', verbose_name='recipients'),
        ),
    ]
