# Generated by Django 5.0.4 on 2024-05-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_remove_mailingmessage_recipients'),
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='recipients',
            field=models.ManyToManyField(to='recipients.recipients', verbose_name='recipients'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='first_datetime',
            field=models.DateTimeField(verbose_name='first_datetime'),
        ),
    ]
