# Generated by Django 5.0.4 on 2024-05-12 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailingsettings_first_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingstatus',
            name='mailing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingsettings', verbose_name='mailing_id'),
        ),
        migrations.AlterField(
            model_name='mailingstatus',
            name='status',
            field=models.TextField(verbose_name='status'),
        ),
    ]
