# Generated by Django 5.0.4 on 2024-05-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailingstatus_mailing_id_alter_mailingstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingstatus',
            name='status',
            field=models.CharField(choices=[('success', 'успешно'), ('fail', 'неуспешно')], default='', max_length=50, verbose_name='статус попытки'),
        ),
    ]
