# Generated by Django 5.0.4 on 2024-05-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailingstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingstatus',
            name='next_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='next_datetime'),
        ),
    ]
