# Generated by Django 5.0.4 on 2024-05-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_mailingstatus_next_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingstatus',
            name='status',
            field=models.CharField(max_length=50, verbose_name='статус попытки'),
        ),
    ]
