# Generated by Django 5.0.4 on 2024-05-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_remove_mailingstatus_next_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='next_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='next_datetime'),
        ),
    ]
