# Generated by Django 4.2.2 on 2024-06-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_alter_mailingsettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='settings_status',
            field=models.CharField(choices=[('Create', 'Создана'), ('Started', 'Отправляется'), ('Done', 'Завершена'), ('Cancel', 'Отменена')], default='Create', max_length=50, verbose_name='settings_status'),
        ),
    ]
