# Generated by Django 5.0.4 on 2024-05-10 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipients',
            name='mailing_settings',
        ),
    ]
