# Generated by Django 4.2.2 on 2024-06-01 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0002_recipients_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipients',
            name='creator',
        ),
    ]
